### ISSUE TITLE
Better avoid SoftwareSerial !

### ISSUE THREAD

**Issue by rin67630** [physee/Victron.Arduino-ESP8266#14]
One should better avoid SoftwareSerial, which has massive performance problems at 19200 Baud.

The better solution is to use Serial.swap() once the ESP is initialized, which swaps the hardware UART on D7 / D8

Then one can "print" using TelnetSerial 

Please look at my fork: https://github.com/rin67630/esp8266-victron-mppt-solarchargecontroller-Telnet

Regards.

**Comment by Booli** [comment]
Hey @rin67630,

Amazing work on the VE on Steroids. I see that still some of my original code of the serial handling is in there. 

Thanks for noting on the SoftwareSerial, this library used software serial for ease of use, our internally used software had multiple available hardware serial.

This code is licensed MIT, so I hope that you will adhere to similar license or at least those parts of the code.

**Comment by rin67630** [comment]
> Hey @rin67630,
> This code is licensed MIT, so I hope that you will adhere to similar license or at least those parts of the code.

Thank you for the hint.
I forked the Victron parser code from Datjan, who I credited in good faith. Let me apologize, if you are the origin of that code
I have changed the credits accordingly.
