### ISSUE TITLE
Can I use the same config file for the 100/50 controller 

### ISSUE THREAD

**Issue by talb85** [physee/Victron.Arduino-ESP8266#6]
hi, i have a 100/50 controller that i want to use, but not sure how to, or if i need to set up the config file differently.  

can anyone offer any assistance with this?

**Comment by deswong** [comment]
You should be fine to modify the config file as required, by changing the num_keywords value, adding the labels and defining the order of the value in the define statements. 

Refer to the VE.Direct Protocol document from Victron to determine the keywords - and you can use a serial port terminal to determine the order if required, and see what data is being presented.
