### ISSUE TITLE
Too much RAM for Arduino

### ISSUE THREAD

**Issue by ortegafernando** [physee/Victron.Arduino-ESP8266#8]
Hi, why value_bytes is 33? As it is used in an 2D array, RAM left is very poor.

Could we use as 2 bytes and save values as INTs ?

Thanks a lot for your work.

**Comment by Booli** [comment]
Yeah, it uses `char` for most of it, as it needs it to read longer lines. You can convert it to `int` for the labels you know that will be `int`. 

I am not maintaining this at the moment, so I highly encourage you to fork this and change it :)
